<?php
$TREE = array (
  0 => 
  array (
    'children' => 
    array (
      0 => 983,
    ),
    'allChildren' => 
    array (
      0 => 983,
    ),
    'childLevels' => 2,
    'hasSubsections' => true,
    'subsections' => 
    array (
      0 => 
      array (
        'sectionId' => '983',
        'parentId' => '982',
        'name' => 'Доставляем в любую точку страны',
        'alias' => 'Доставляем в любую точку страны',
        'fileName' => 'dostavlyaem-v-lyubuyu-tochku-strany',
        'type' => 'tree',
        'type_content' => 'articles',
        'url' => 'http://secondworld.life/en//dostavlyaem-v-lyubuyu-tochku-strany/',
        'section_icon' => '',
        'dop' => '',
        'hasImage' => '0',
        'summary' => '<p>Берем на себя все этапы транспортировки: наши логисты выстроят оптимальную схему доставки, а водители доставят груз быстро и сохранно.</p>',
        'content' => '<p>[]</p>
<p>Скомплектуем заказ</p>
<p>[]</p>
<p>Составим маршрут</p>
<p>[]</p>
<p>Оформим документы</p>
<p>[]</p>
<p>Оформим документы</p>',
        'content_two' => '',
        'status' => 'visible',
        'meta_title' => 'Доставляем в любую точку страны',
        'keywords' => 'Доставляем в любую точку страны',
        'description' => 'Доставляем в любую точку страны',
        'templateName' => '',
        'subTemplateName' => '',
        'artTemplateName' => '',
        'isCached' => '0',
        'cacheTime' => '1',
        'cachePeriod' => '86400',
        'commentsEnabled' => '0',
        'subIsCached' => '0',
        'subCacheTime' => '1',
        'subCachePeriod' => '86400',
        'subCommentsEnabled' => '0',
        'artIsCached' => '0',
        'artCacheTime' => '1',
        'artCachePeriod' => '86400',
        'sortOrder' => '1',
        'addedBy' => '9',
        'addedOn' => '2021-06-02 07:51:10',
        'modifiedBy' => '1',
        'modifiedOn' => '2022-08-11 10:50:34',
        'toSlider' => '0',
        'toMain' => '0',
        'top_menu' => '1',
        'footer_menu' => '0',
        'top_submenu' => '0',
        'photo_gallery' => '1',
        'footerMenu' => '0',
        'menus' => '',
        'isFeatured' => '0',
        'block' => '',
        'parents' => 
        array (
          0 => '982',
        ),
        'childLevels' => 0,
        'level' => 2,
        'path' => 'http://secondworld.life/en//dostavlyaem-v-lyubuyu-tochku-strany',
        'dir' => 'dostavlyaem-v-lyubuyu-tochku-strany',
        'hasSubsections' => false,
      ),
    ),
  ),
  1 => 
  array (
    'sectionId' => '1',
    'parentId' => '0',
    'name' => 'Главная',
    'alias' => 'Join',
    'fileName' => 'index',
    'type' => 'plain',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/',
    'section_icon' => 'Release platforms:',
    'dop' => 'Contact Us:',
    'hasImage' => '1',
    'summary' => '<p>[https://facebook.com]</p>
<p>/images/facebook.svg</p>
<p>[https://facebook.com]</p>
<p>/images/telegram.svg</p>',
    'content' => '<p>[https://facebook.com]</p>
<p>/images/steam.svg</p>
<p>[https://facebook.com]</p>
<p>/images/windows.svg</p>
<p>[https://facebook.com]</p>
<p>/images/epic-games.svg</p>',
    'content_two' => '<p>[https://facebook.com]</p>
<p>/images/ios.svg</p>
<p>[https://facebook.com]</p>
<p>/images/android.svg</p>
<p>[https://facebook.com]</p>
<p>/images/playstation.svg</p>
<p>[https://facebook.com]</p>
<p>/images/xbox.svg</p>',
    'status' => 'hidden',
    'meta_title' => 'Главная',
    'keywords' => 'Главная',
    'description' => 'Главная',
    'templateName' => 'index.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '7',
    'addedOn' => '2018-08-10 07:29:18',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:27:54',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/index',
    'dir' => 'index',
    'hasSubsections' => false,
  ),
  2 => 
  array (
    'sectionId' => '1003',
    'parentId' => '0',
    'name' => 'Our team',
    'alias' => 'Our tea',
    'fileName' => 'our-team',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/our-team/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '<p>[How to play?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span><span></span></p>
<p>[How to sign up in closed beta?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span></p>
<p>[Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consectetur vitae, cursus <span>viverra at proin enim egestas</span>?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span></p>',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Our team',
    'keywords' => 'Our team',
    'description' => 'Our team',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '2',
    'addedBy' => '1',
    'addedOn' => '2022-08-13 12:58:59',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-15 12:05:46',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/our-team',
    'dir' => 'our-team',
    'hasSubsections' => false,
  ),
  3 => 
  array (
    'sectionId' => '1001',
    'parentId' => '0',
    'name' => 'Realesed works',
    'alias' => 'Realesed works',
    'fileName' => 'realesed-works',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/realesed-works/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Realesed works',
    'keywords' => 'Realesed works',
    'description' => 'Realesed works',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '3',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:55:07',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:23:38',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/realesed-works',
    'dir' => 'realesed-works',
    'hasSubsections' => false,
  ),
  4 => 
  array (
    'sectionId' => '1000',
    'parentId' => '0',
    'name' => 'Здесь ссылка на whitepaper',
    'alias' => 'https://google.com',
    'fileName' => 'statistika-',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/statistika-/',
    'section_icon' => 'Watch whitepaper',
    'dop' => '#',
    'hasImage' => '1',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Статистика ',
    'keywords' => 'Статистика ',
    'description' => 'Статистика ',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '4',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:51:58',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:22:11',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/statistika-',
    'dir' => 'statistika-',
    'hasSubsections' => false,
  ),
  5 => 
  array (
    'sectionId' => '999',
    'parentId' => '0',
    'name' => 'Tokenomics',
    'alias' => 'Токеномика ',
    'fileName' => 'tokenomika-',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/tokenomika-/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Токеномика ',
    'keywords' => 'Токеномика ',
    'description' => 'Токеномика ',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '5',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:43:25',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:19:15',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/tokenomika-',
    'dir' => 'tokenomika-',
    'hasSubsections' => false,
  ),
  6 => 
  array (
    'sectionId' => '998',
    'parentId' => '0',
    'name' => 'Информация',
    'alias' => 'Информация',
    'fileName' => 'informatsiya',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/informatsiya/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Информация',
    'keywords' => 'Информация',
    'description' => 'Информация',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '6',
    'addedBy' => '1',
    'addedOn' => '2022-08-11 11:34:26',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-11 13:26:42',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/informatsiya',
    'dir' => 'informatsiya',
    'hasSubsections' => false,
  ),
  7 => 
  array (
    'sectionId' => '996',
    'parentId' => '0',
    'name' => 'METAWORLD SECONDWORLD',
    'alias' => 'METAWORLD SECONDWORLD',
    'fileName' => 'metaworld-secondworld',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/metaworld-secondworld/',
    'section_icon' => 'Watch trailer',
    'dop' => 'https://www.youtube.com',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'METAWORLD SECONDWORLD',
    'keywords' => 'METAWORLD SECONDWORLD',
    'description' => 'METAWORLD SECONDWORLD',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '7',
    'addedBy' => '1',
    'addedOn' => '2022-08-11 10:58:44',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 07:47:45',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/metaworld-secondworld',
    'dir' => 'metaworld-secondworld',
    'hasSubsections' => false,
  ),
  8 => 
  array (
    'sectionId' => '975',
    'parentId' => '0',
    'name' => 'News',
    'alias' => '#news',
    'fileName' => 'novosti-',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/novosti-/',
    'section_icon' => '22.12.2022',
    'dop' => 'Watch footage trailer',
    'hasImage' => '1',
    'summary' => '<div>
<div><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet</span></div>
</div>',
    'content' => '<p>https://google.com</p>',
    'content_two' => '<p>https://google.com</p>',
    'status' => 'visible',
    'meta_title' => 'Новости ',
    'keywords' => 'Новости ',
    'description' => 'Новости ',
    'templateName' => 'section-about.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '8',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 07:11:42',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:37:21',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '1',
    'photo_gallery' => '1',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 1,
    'level' => 1,
    'path' => 'http://secondworld.life/en/novosti-',
    'dir' => 'novosti-',
    'children' => 
    array (
      0 => 985,
      1 => 986,
      2 => 987,
    ),
    'allChildren' => 
    array (
      0 => 985,
      1 => 986,
      2 => 987,
    ),
    'hasSubsections' => false,
    'subsections' => 
    array (
      0 => 
      array (
        'sectionId' => '985',
        'parentId' => '975',
        'name' => 'Виды деятельности',
        'alias' => 'Виды деятельности',
        'fileName' => 'vidy-deyatelnosti',
        'type' => 'tree',
        'type_content' => 'articles',
        'url' => 'http://secondworld.life/en/novosti-/vidy-deyatelnosti/',
        'section_icon' => '',
        'dop' => '',
        'hasImage' => '1',
        'summary' => '<p>[]</p>
<p>Торговля металлическими рудами</p>
<p>[]</p>
<p>Торговля сталью и металлопродукцией</p>
<p>[]</p>
<p>Торговля цветными металлами</p>
<p>[]</p>
<p>Торговля металлическими сплавами</p>
<p>[]</p>
<p>Торговля строительными материалами</p>
<p>[]</p>
<p>Торговля строительной металлопродукцией</p>
<p>[]</p>
<p>Торговля ломом и металлическими отходами</p>',
        'content' => '',
        'content_two' => '',
        'status' => 'visible',
        'meta_title' => 'Виды деятельности',
        'keywords' => 'Виды деятельности',
        'description' => 'Виды деятельности',
        'templateName' => '',
        'subTemplateName' => '',
        'artTemplateName' => '',
        'isCached' => '0',
        'cacheTime' => '1',
        'cachePeriod' => '86400',
        'commentsEnabled' => '0',
        'subIsCached' => '0',
        'subCacheTime' => '1',
        'subCachePeriod' => '86400',
        'subCommentsEnabled' => '0',
        'artIsCached' => '0',
        'artCacheTime' => '1',
        'artCachePeriod' => '86400',
        'sortOrder' => '1',
        'addedBy' => '9',
        'addedOn' => '2021-06-02 09:34:00',
        'modifiedBy' => '9',
        'modifiedOn' => '2021-06-02 09:34:25',
        'toSlider' => '0',
        'toMain' => '0',
        'top_menu' => '1',
        'footer_menu' => '0',
        'top_submenu' => '0',
        'photo_gallery' => '0',
        'footerMenu' => '0',
        'menus' => '',
        'isFeatured' => '0',
        'block' => '',
        'parents' => 
        array (
          0 => '975',
        ),
        'childLevels' => 0,
        'level' => 2,
        'path' => 'http://secondworld.life/en/novosti-/vidy-deyatelnosti',
        'dir' => 'novosti-/vidy-deyatelnosti',
        'hasSubsections' => false,
      ),
      1 => 
      array (
        'sectionId' => '986',
        'parentId' => '975',
        'name' => 'Преимущества',
        'alias' => 'Преимущества',
        'fileName' => 'preimuschestva',
        'type' => 'tree',
        'type_content' => 'articles',
        'url' => 'http://secondworld.life/en/novosti-/preimuschestva/',
        'section_icon' => '',
        'dop' => '',
        'hasImage' => '0',
        'summary' => '',
        'content' => '',
        'content_two' => '',
        'status' => 'visible',
        'meta_title' => 'Преимущества',
        'keywords' => 'Преимущества',
        'description' => 'Преимущества',
        'templateName' => '',
        'subTemplateName' => '',
        'artTemplateName' => '',
        'isCached' => '0',
        'cacheTime' => '1',
        'cachePeriod' => '86400',
        'commentsEnabled' => '0',
        'subIsCached' => '0',
        'subCacheTime' => '1',
        'subCachePeriod' => '86400',
        'subCommentsEnabled' => '0',
        'artIsCached' => '0',
        'artCacheTime' => '1',
        'artCachePeriod' => '86400',
        'sortOrder' => '2',
        'addedBy' => '9',
        'addedOn' => '2021-06-02 09:37:16',
        'modifiedBy' => '9',
        'modifiedOn' => '2021-06-02 09:37:16',
        'toSlider' => '0',
        'toMain' => '0',
        'top_menu' => '1',
        'footer_menu' => '0',
        'top_submenu' => '0',
        'photo_gallery' => '0',
        'footerMenu' => '0',
        'menus' => '',
        'isFeatured' => '0',
        'block' => '',
        'parents' => 
        array (
          0 => '975',
        ),
        'childLevels' => 0,
        'level' => 2,
        'path' => 'http://secondworld.life/en/novosti-/preimuschestva',
        'dir' => 'novosti-/preimuschestva',
        'hasSubsections' => false,
      ),
      2 => 
      array (
        'sectionId' => '987',
        'parentId' => '975',
        'name' => 'География работы',
        'alias' => 'География работы',
        'fileName' => 'geografiya-raboty',
        'type' => 'tree',
        'type_content' => 'articles',
        'url' => 'http://secondworld.life/en/novosti-/geografiya-raboty/',
        'section_icon' => '',
        'dop' => '',
        'hasImage' => '1',
        'summary' => '<p>Наш филиал в Узбекистане отмечен на карте. Вы можете забрать товары со склада или заказать доставку.</p>',
        'content' => '<p>[]</p>
<p>Казахстан</p>
<p>[]</p>
<p>Россия</p>
<p>[]</p>
<p>Узбекистан</p>
<p>[]</p>
<p>Киргизия</p>
<p>[]</p>
<p>Таджикистан</p>
<p>[]</p>
<p>Китай</p>',
        'content_two' => '',
        'status' => 'visible',
        'meta_title' => 'География работы',
        'keywords' => 'География работы',
        'description' => 'География работы',
        'templateName' => '',
        'subTemplateName' => '',
        'artTemplateName' => '',
        'isCached' => '0',
        'cacheTime' => '1',
        'cachePeriod' => '86400',
        'commentsEnabled' => '0',
        'subIsCached' => '0',
        'subCacheTime' => '1',
        'subCachePeriod' => '86400',
        'subCommentsEnabled' => '0',
        'artIsCached' => '0',
        'artCacheTime' => '1',
        'artCachePeriod' => '86400',
        'sortOrder' => '3',
        'addedBy' => '9',
        'addedOn' => '2021-06-02 09:45:48',
        'modifiedBy' => '9',
        'modifiedOn' => '2021-06-02 12:13:44',
        'toSlider' => '0',
        'toMain' => '0',
        'top_menu' => '1',
        'footer_menu' => '0',
        'top_submenu' => '0',
        'photo_gallery' => '0',
        'footerMenu' => '0',
        'menus' => '',
        'isFeatured' => '0',
        'block' => '',
        'parents' => 
        array (
          0 => '975',
        ),
        'childLevels' => 0,
        'level' => 2,
        'path' => 'http://secondworld.life/en/novosti-/geografiya-raboty',
        'dir' => 'novosti-/geografiya-raboty',
        'hasSubsections' => false,
      ),
    ),
  ),
  9 => 
  array (
    'sectionId' => '984',
    'parentId' => '0',
    'name' => 'Roadmap',
    'alias' => '#roadmap',
    'fileName' => 'roadmap',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/roadmap/',
    'section_icon' => '',
    'dop' => 'We offer to you our roadmap of developments',
    'hasImage' => '1',
    'summary' => '<p>Во время консультации наш менеджер ответит на все вопросы</p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Roadmap',
    'keywords' => 'Roadmap',
    'description' => 'Roadmap',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '9',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 08:35:21',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:15:56',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/roadmap',
    'dir' => 'roadmap',
    'hasSubsections' => false,
  ),
  10 => 
  array (
    'sectionId' => '988',
    'parentId' => '0',
    'name' => 'FAQ',
    'alias' => '#faq',
    'fileName' => 'faq',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '<p>[]</p>
<p>Рулоны</p>
<p>[]</p>
<p>Электроды, огнеупоры и ферросплавы</p>
<p>[]</p>
<p>Стальные заготовки</p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'FAQ',
    'keywords' => 'FAQ',
    'description' => 'FAQ',
    'templateName' => 'section-production.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '10',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 10:05:28',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:41:56',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '1',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 2,
    'level' => 1,
    'path' => 'http://secondworld.life/en/faq',
    'dir' => 'faq',
    'children' => 
    array (
      0 => 991,
    ),
    'allChildren' => 
    array (
      0 => 991,
      1 => 992,
      2 => 993,
      3 => 994,
    ),
    'hasSubsections' => false,
    'subsections' => 
    array (
      0 => 
      array (
        'sectionId' => '991',
        'parentId' => '988',
        'name' => 'Слайдер',
        'alias' => 'Слайдер',
        'fileName' => 'slajder',
        'type' => 'tree',
        'type_content' => 'articles',
        'url' => 'http://secondworld.life/en/faq/slajder/',
        'section_icon' => '',
        'dop' => '',
        'hasImage' => '0',
        'summary' => '',
        'content' => '',
        'content_two' => '',
        'status' => 'visible',
        'meta_title' => 'Слайдер',
        'keywords' => 'Слайдер',
        'description' => 'Слайдер',
        'templateName' => '',
        'subTemplateName' => '',
        'artTemplateName' => '',
        'isCached' => '0',
        'cacheTime' => '1',
        'cachePeriod' => '86400',
        'commentsEnabled' => '0',
        'subIsCached' => '0',
        'subCacheTime' => '1',
        'subCachePeriod' => '86400',
        'subCommentsEnabled' => '0',
        'artIsCached' => '0',
        'artCacheTime' => '1',
        'artCachePeriod' => '86400',
        'sortOrder' => '1',
        'addedBy' => '9',
        'addedOn' => '2021-06-02 11:48:01',
        'modifiedBy' => '9',
        'modifiedOn' => '2021-06-02 11:48:01',
        'toSlider' => '0',
        'toMain' => '0',
        'top_menu' => '1',
        'footer_menu' => '0',
        'top_submenu' => '0',
        'photo_gallery' => '0',
        'footerMenu' => '0',
        'menus' => '',
        'isFeatured' => '0',
        'block' => '',
        'parents' => 
        array (
          0 => '988',
        ),
        'childLevels' => 1,
        'level' => 2,
        'path' => 'http://secondworld.life/en/faq/slajder',
        'dir' => 'faq/slajder',
        'children' => 
        array (
          0 => 992,
          1 => 993,
          2 => 994,
        ),
        'allChildren' => 
        array (
          0 => 992,
          1 => 993,
          2 => 994,
        ),
        'hasSubsections' => false,
        'subsections' => 
        array (
          0 => 
          array (
            'sectionId' => '994',
            'parentId' => '991',
            'name' => 'Треугольная заготовка',
            'alias' => 'Треугольная заготовк',
            'fileName' => 'treugolnaya-zagotovk',
            'type' => 'tree',
            'type_content' => 'articles',
            'url' => 'http://secondworld.life/en/faq/slajder/treugolnaya-zagotovk/',
            'section_icon' => '',
            'dop' => '',
            'hasImage' => '1',
            'summary' => '',
            'content' => '',
            'content_two' => '',
            'status' => 'visible',
            'meta_title' => 'Треугольная заготовк',
            'keywords' => 'Треугольная заготовк',
            'description' => 'Треугольная заготовк',
            'templateName' => '',
            'subTemplateName' => '',
            'artTemplateName' => '',
            'isCached' => '0',
            'cacheTime' => '1',
            'cachePeriod' => '86400',
            'commentsEnabled' => '0',
            'subIsCached' => '0',
            'subCacheTime' => '1',
            'subCachePeriod' => '86400',
            'subCommentsEnabled' => '0',
            'artIsCached' => '0',
            'artCacheTime' => '1',
            'artCachePeriod' => '86400',
            'sortOrder' => '3',
            'addedBy' => '9',
            'addedOn' => '2021-06-02 11:49:32',
            'modifiedBy' => '9',
            'modifiedOn' => '2021-06-02 11:49:38',
            'toSlider' => '0',
            'toMain' => '0',
            'top_menu' => '1',
            'footer_menu' => '0',
            'top_submenu' => '0',
            'photo_gallery' => '0',
            'footerMenu' => '0',
            'menus' => '',
            'isFeatured' => '0',
            'block' => '',
            'parents' => 
            array (
              0 => '988',
              1 => '991',
            ),
            'childLevels' => 0,
            'level' => 3,
            'path' => 'http://secondworld.life/en/faq/slajder/treugolnaya-zagotovk',
            'dir' => 'faq/slajder/treugolnaya-zagotovk',
            'hasSubsections' => false,
          ),
          1 => 
          array (
            'sectionId' => '993',
            'parentId' => '991',
            'name' => 'Квадратная заготовка',
            'alias' => 'Квадратная заготовк',
            'fileName' => 'kvadratnaya-zagotovk',
            'type' => 'tree',
            'type_content' => 'articles',
            'url' => 'http://secondworld.life/en/faq/slajder/kvadratnaya-zagotovk/',
            'section_icon' => '',
            'dop' => '',
            'hasImage' => '1',
            'summary' => '',
            'content' => '',
            'content_two' => '',
            'status' => 'visible',
            'meta_title' => 'Квадратная заготовк',
            'keywords' => 'Квадратная заготовк',
            'description' => 'Квадратная заготовк',
            'templateName' => '',
            'subTemplateName' => '',
            'artTemplateName' => '',
            'isCached' => '0',
            'cacheTime' => '1',
            'cachePeriod' => '86400',
            'commentsEnabled' => '0',
            'subIsCached' => '0',
            'subCacheTime' => '1',
            'subCachePeriod' => '86400',
            'subCommentsEnabled' => '0',
            'artIsCached' => '0',
            'artCacheTime' => '1',
            'artCachePeriod' => '86400',
            'sortOrder' => '2',
            'addedBy' => '9',
            'addedOn' => '2021-06-02 11:49:18',
            'modifiedBy' => '9',
            'modifiedOn' => '2021-06-02 11:49:23',
            'toSlider' => '0',
            'toMain' => '0',
            'top_menu' => '1',
            'footer_menu' => '0',
            'top_submenu' => '0',
            'photo_gallery' => '0',
            'footerMenu' => '0',
            'menus' => '',
            'isFeatured' => '0',
            'block' => '',
            'parents' => 
            array (
              0 => '988',
              1 => '991',
            ),
            'childLevels' => 0,
            'level' => 3,
            'path' => 'http://secondworld.life/en/faq/slajder/kvadratnaya-zagotovk',
            'dir' => 'faq/slajder/kvadratnaya-zagotovk',
            'hasSubsections' => false,
          ),
          2 => 
          array (
            'sectionId' => '992',
            'parentId' => '991',
            'name' => 'Прямоугольная заготовка',
            'alias' => 'Прямоугольная заготовка',
            'fileName' => 'pryamougolnaya-zagotovka',
            'type' => 'tree',
            'type_content' => 'articles',
            'url' => 'http://secondworld.life/en/faq/slajder/pryamougolnaya-zagotovka/',
            'section_icon' => '',
            'dop' => '',
            'hasImage' => '1',
            'summary' => '',
            'content' => '',
            'content_two' => '',
            'status' => 'visible',
            'meta_title' => 'Прямоугольная заготовка',
            'keywords' => 'Прямоугольная заготовка',
            'description' => 'Прямоугольная заготовка',
            'templateName' => '',
            'subTemplateName' => '',
            'artTemplateName' => '',
            'isCached' => '0',
            'cacheTime' => '1',
            'cachePeriod' => '86400',
            'commentsEnabled' => '0',
            'subIsCached' => '0',
            'subCacheTime' => '1',
            'subCachePeriod' => '86400',
            'subCommentsEnabled' => '0',
            'artIsCached' => '0',
            'artCacheTime' => '1',
            'artCachePeriod' => '86400',
            'sortOrder' => '1',
            'addedBy' => '9',
            'addedOn' => '2021-06-02 11:48:07',
            'modifiedBy' => '9',
            'modifiedOn' => '2021-06-02 11:49:03',
            'toSlider' => '0',
            'toMain' => '0',
            'top_menu' => '1',
            'footer_menu' => '0',
            'top_submenu' => '0',
            'photo_gallery' => '0',
            'footerMenu' => '0',
            'menus' => '',
            'isFeatured' => '0',
            'block' => '',
            'parents' => 
            array (
              0 => '988',
              1 => '991',
            ),
            'childLevels' => 0,
            'level' => 3,
            'path' => 'http://secondworld.life/en/faq/slajder/pryamougolnaya-zagotovka',
            'dir' => 'faq/slajder/pryamougolnaya-zagotovka',
            'hasSubsections' => false,
          ),
        ),
      ),
    ),
  ),
  11 => 
  array (
    'sectionId' => '989',
    'parentId' => '0',
    'name' => 'About us',
    'alias' => '#about',
    'fileName' => 'about-us',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/about-us/',
    'section_icon' => '',
    'dop' => 'SECONDWORLD',
    'hasImage' => '1',
    'summary' => '<p>Second<span class="text-primary">world</span></p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'About us',
    'keywords' => 'About us',
    'description' => 'About us',
    'templateName' => 'section-contacts.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '11',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 10:05:42',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 07:21:10',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '1',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/about-us',
    'dir' => 'about-us',
    'hasSubsections' => false,
  ),
);
$smarty->assignByRef('TREE', $TREE);
$SECTIONS = array (
  '' => NULL,
  983 => 
  array (
    'sectionId' => '983',
    'parentId' => '982',
    'name' => 'Доставляем в любую точку страны',
    'alias' => 'Доставляем в любую точку страны',
    'fileName' => 'dostavlyaem-v-lyubuyu-tochku-strany',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en//dostavlyaem-v-lyubuyu-tochku-strany/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '<p>Берем на себя все этапы транспортировки: наши логисты выстроят оптимальную схему доставки, а водители доставят груз быстро и сохранно.</p>',
    'content' => '<p>[]</p>
<p>Скомплектуем заказ</p>
<p>[]</p>
<p>Составим маршрут</p>
<p>[]</p>
<p>Оформим документы</p>
<p>[]</p>
<p>Оформим документы</p>',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Доставляем в любую точку страны',
    'keywords' => 'Доставляем в любую точку страны',
    'description' => 'Доставляем в любую точку страны',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 07:51:10',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-11 10:50:34',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '1',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '982',
    ),
    'childLevels' => 0,
    'level' => 2,
    'path' => 'http://secondworld.life/en//dostavlyaem-v-lyubuyu-tochku-strany',
    'dir' => 'dostavlyaem-v-lyubuyu-tochku-strany',
  ),
  1 => 
  array (
    'sectionId' => '1',
    'parentId' => '0',
    'name' => 'Главная',
    'alias' => 'Join',
    'fileName' => 'index',
    'type' => 'plain',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/',
    'section_icon' => 'Release platforms:',
    'dop' => 'Contact Us:',
    'hasImage' => '1',
    'summary' => '<p>[https://facebook.com]</p>
<p>/images/facebook.svg</p>
<p>[https://facebook.com]</p>
<p>/images/telegram.svg</p>',
    'content' => '<p>[https://facebook.com]</p>
<p>/images/steam.svg</p>
<p>[https://facebook.com]</p>
<p>/images/windows.svg</p>
<p>[https://facebook.com]</p>
<p>/images/epic-games.svg</p>',
    'content_two' => '<p>[https://facebook.com]</p>
<p>/images/ios.svg</p>
<p>[https://facebook.com]</p>
<p>/images/android.svg</p>
<p>[https://facebook.com]</p>
<p>/images/playstation.svg</p>
<p>[https://facebook.com]</p>
<p>/images/xbox.svg</p>',
    'status' => 'hidden',
    'meta_title' => 'Главная',
    'keywords' => 'Главная',
    'description' => 'Главная',
    'templateName' => 'index.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '7',
    'addedOn' => '2018-08-10 07:29:18',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:27:54',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/index',
    'dir' => 'index',
  ),
  1003 => 
  array (
    'sectionId' => '1003',
    'parentId' => '0',
    'name' => 'Our team',
    'alias' => 'Our tea',
    'fileName' => 'our-team',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/our-team/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '<p>[How to play?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span><span></span></p>
<p>[How to sign up in closed beta?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span></p>
<p>[Lorem ipsum dolor sit amet, consectetur adipiscing elit. Consectetur vitae, cursus <span>viverra at proin enim egestas</span>?]</p>
<p><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet consectetur dolor a, tincidunt in. Pretium integer scelerisque sit enim velit, nascetur sit diam rhoncus. Ut natoque semper elementum fringilla purus. Sed viverra gravida sed proin ornare. Tortor sed nunc aliquam sit.</span></p>',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Our team',
    'keywords' => 'Our team',
    'description' => 'Our team',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '2',
    'addedBy' => '1',
    'addedOn' => '2022-08-13 12:58:59',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-15 12:05:46',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/our-team',
    'dir' => 'our-team',
  ),
  1001 => 
  array (
    'sectionId' => '1001',
    'parentId' => '0',
    'name' => 'Realesed works',
    'alias' => 'Realesed works',
    'fileName' => 'realesed-works',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/realesed-works/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Realesed works',
    'keywords' => 'Realesed works',
    'description' => 'Realesed works',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '3',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:55:07',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:23:38',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/realesed-works',
    'dir' => 'realesed-works',
  ),
  1000 => 
  array (
    'sectionId' => '1000',
    'parentId' => '0',
    'name' => 'Здесь ссылка на whitepaper',
    'alias' => 'https://google.com',
    'fileName' => 'statistika-',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/statistika-/',
    'section_icon' => 'Watch whitepaper',
    'dop' => '#',
    'hasImage' => '1',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Статистика ',
    'keywords' => 'Статистика ',
    'description' => 'Статистика ',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '4',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:51:58',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:22:11',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/statistika-',
    'dir' => 'statistika-',
  ),
  999 => 
  array (
    'sectionId' => '999',
    'parentId' => '0',
    'name' => 'Tokenomics',
    'alias' => 'Токеномика ',
    'fileName' => 'tokenomika-',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/tokenomika-/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Токеномика ',
    'keywords' => 'Токеномика ',
    'description' => 'Токеномика ',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '5',
    'addedBy' => '1',
    'addedOn' => '2022-08-12 07:43:25',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:19:15',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/tokenomika-',
    'dir' => 'tokenomika-',
  ),
  998 => 
  array (
    'sectionId' => '998',
    'parentId' => '0',
    'name' => 'Информация',
    'alias' => 'Информация',
    'fileName' => 'informatsiya',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/informatsiya/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'Информация',
    'keywords' => 'Информация',
    'description' => 'Информация',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '6',
    'addedBy' => '1',
    'addedOn' => '2022-08-11 11:34:26',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-11 13:26:42',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/informatsiya',
    'dir' => 'informatsiya',
  ),
  996 => 
  array (
    'sectionId' => '996',
    'parentId' => '0',
    'name' => 'METAWORLD SECONDWORLD',
    'alias' => 'METAWORLD SECONDWORLD',
    'fileName' => 'metaworld-secondworld',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/metaworld-secondworld/',
    'section_icon' => 'Watch trailer',
    'dop' => 'https://www.youtube.com',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'hidden',
    'meta_title' => 'METAWORLD SECONDWORLD',
    'keywords' => 'METAWORLD SECONDWORLD',
    'description' => 'METAWORLD SECONDWORLD',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '7',
    'addedBy' => '1',
    'addedOn' => '2022-08-11 10:58:44',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 07:47:45',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '0',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/metaworld-secondworld',
    'dir' => 'metaworld-secondworld',
  ),
  975 => 
  array (
    'sectionId' => '975',
    'parentId' => '0',
    'name' => 'News',
    'alias' => '#news',
    'fileName' => 'novosti-',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/novosti-/',
    'section_icon' => '22.12.2022',
    'dop' => 'Watch footage trailer',
    'hasImage' => '1',
    'summary' => '<div>
<div><span>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Orci at bibendum tristique tristique in et. Nunc vel quis aenean imperdiet</span></div>
</div>',
    'content' => '<p>https://google.com</p>',
    'content_two' => '<p>https://google.com</p>',
    'status' => 'visible',
    'meta_title' => 'Новости ',
    'keywords' => 'Новости ',
    'description' => 'Новости ',
    'templateName' => 'section-about.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '8',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 07:11:42',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:37:21',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '1',
    'photo_gallery' => '1',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 1,
    'level' => 1,
    'path' => 'http://secondworld.life/en/novosti-',
    'dir' => 'novosti-',
    'children' => 
    array (
      0 => 985,
      1 => 986,
      2 => 987,
    ),
    'allChildren' => 
    array (
      0 => 985,
      1 => 986,
      2 => 987,
    ),
  ),
  987 => 
  array (
    'sectionId' => '987',
    'parentId' => '975',
    'name' => 'География работы',
    'alias' => 'География работы',
    'fileName' => 'geografiya-raboty',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/novosti-/geografiya-raboty/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '1',
    'summary' => '<p>Наш филиал в Узбекистане отмечен на карте. Вы можете забрать товары со склада или заказать доставку.</p>',
    'content' => '<p>[]</p>
<p>Казахстан</p>
<p>[]</p>
<p>Россия</p>
<p>[]</p>
<p>Узбекистан</p>
<p>[]</p>
<p>Киргизия</p>
<p>[]</p>
<p>Таджикистан</p>
<p>[]</p>
<p>Китай</p>',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'География работы',
    'keywords' => 'География работы',
    'description' => 'География работы',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '3',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 09:45:48',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 12:13:44',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '975',
    ),
    'childLevels' => 0,
    'level' => 2,
    'path' => 'http://secondworld.life/en/novosti-/geografiya-raboty',
    'dir' => 'novosti-/geografiya-raboty',
  ),
  986 => 
  array (
    'sectionId' => '986',
    'parentId' => '975',
    'name' => 'Преимущества',
    'alias' => 'Преимущества',
    'fileName' => 'preimuschestva',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/novosti-/preimuschestva/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Преимущества',
    'keywords' => 'Преимущества',
    'description' => 'Преимущества',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '2',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 09:37:16',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 09:37:16',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '975',
    ),
    'childLevels' => 0,
    'level' => 2,
    'path' => 'http://secondworld.life/en/novosti-/preimuschestva',
    'dir' => 'novosti-/preimuschestva',
  ),
  985 => 
  array (
    'sectionId' => '985',
    'parentId' => '975',
    'name' => 'Виды деятельности',
    'alias' => 'Виды деятельности',
    'fileName' => 'vidy-deyatelnosti',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/novosti-/vidy-deyatelnosti/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '1',
    'summary' => '<p>[]</p>
<p>Торговля металлическими рудами</p>
<p>[]</p>
<p>Торговля сталью и металлопродукцией</p>
<p>[]</p>
<p>Торговля цветными металлами</p>
<p>[]</p>
<p>Торговля металлическими сплавами</p>
<p>[]</p>
<p>Торговля строительными материалами</p>
<p>[]</p>
<p>Торговля строительной металлопродукцией</p>
<p>[]</p>
<p>Торговля ломом и металлическими отходами</p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Виды деятельности',
    'keywords' => 'Виды деятельности',
    'description' => 'Виды деятельности',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 09:34:00',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 09:34:25',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '975',
    ),
    'childLevels' => 0,
    'level' => 2,
    'path' => 'http://secondworld.life/en/novosti-/vidy-deyatelnosti',
    'dir' => 'novosti-/vidy-deyatelnosti',
  ),
  984 => 
  array (
    'sectionId' => '984',
    'parentId' => '0',
    'name' => 'Roadmap',
    'alias' => '#roadmap',
    'fileName' => 'roadmap',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/roadmap/',
    'section_icon' => '',
    'dop' => 'We offer to you our roadmap of developments',
    'hasImage' => '1',
    'summary' => '<p>Во время консультации наш менеджер ответит на все вопросы</p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Roadmap',
    'keywords' => 'Roadmap',
    'description' => 'Roadmap',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '9',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 08:35:21',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:15:56',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/roadmap',
    'dir' => 'roadmap',
  ),
  988 => 
  array (
    'sectionId' => '988',
    'parentId' => '0',
    'name' => 'FAQ',
    'alias' => '#faq',
    'fileName' => 'faq',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '<p>[]</p>
<p>Рулоны</p>
<p>[]</p>
<p>Электроды, огнеупоры и ферросплавы</p>
<p>[]</p>
<p>Стальные заготовки</p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'FAQ',
    'keywords' => 'FAQ',
    'description' => 'FAQ',
    'templateName' => 'section-production.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '10',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 10:05:28',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 09:41:56',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '1',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 2,
    'level' => 1,
    'path' => 'http://secondworld.life/en/faq',
    'dir' => 'faq',
    'children' => 
    array (
      0 => 991,
    ),
    'allChildren' => 
    array (
      0 => 991,
      1 => 992,
      2 => 993,
      3 => 994,
    ),
  ),
  991 => 
  array (
    'sectionId' => '991',
    'parentId' => '988',
    'name' => 'Слайдер',
    'alias' => 'Слайдер',
    'fileName' => 'slajder',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/slajder/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '0',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Слайдер',
    'keywords' => 'Слайдер',
    'description' => 'Слайдер',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 11:48:01',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 11:48:01',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '988',
    ),
    'childLevels' => 1,
    'level' => 2,
    'path' => 'http://secondworld.life/en/faq/slajder',
    'dir' => 'faq/slajder',
    'children' => 
    array (
      0 => 992,
      1 => 993,
      2 => 994,
    ),
    'allChildren' => 
    array (
      0 => 992,
      1 => 993,
      2 => 994,
    ),
  ),
  994 => 
  array (
    'sectionId' => '994',
    'parentId' => '991',
    'name' => 'Треугольная заготовка',
    'alias' => 'Треугольная заготовк',
    'fileName' => 'treugolnaya-zagotovk',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/slajder/treugolnaya-zagotovk/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '1',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Треугольная заготовк',
    'keywords' => 'Треугольная заготовк',
    'description' => 'Треугольная заготовк',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '3',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 11:49:32',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 11:49:38',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '988',
      1 => '991',
    ),
    'childLevels' => 0,
    'level' => 3,
    'path' => 'http://secondworld.life/en/faq/slajder/treugolnaya-zagotovk',
    'dir' => 'faq/slajder/treugolnaya-zagotovk',
  ),
  993 => 
  array (
    'sectionId' => '993',
    'parentId' => '991',
    'name' => 'Квадратная заготовка',
    'alias' => 'Квадратная заготовк',
    'fileName' => 'kvadratnaya-zagotovk',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/slajder/kvadratnaya-zagotovk/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '1',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Квадратная заготовк',
    'keywords' => 'Квадратная заготовк',
    'description' => 'Квадратная заготовк',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '2',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 11:49:18',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 11:49:23',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '988',
      1 => '991',
    ),
    'childLevels' => 0,
    'level' => 3,
    'path' => 'http://secondworld.life/en/faq/slajder/kvadratnaya-zagotovk',
    'dir' => 'faq/slajder/kvadratnaya-zagotovk',
  ),
  992 => 
  array (
    'sectionId' => '992',
    'parentId' => '991',
    'name' => 'Прямоугольная заготовка',
    'alias' => 'Прямоугольная заготовка',
    'fileName' => 'pryamougolnaya-zagotovka',
    'type' => 'tree',
    'type_content' => 'articles',
    'url' => 'http://secondworld.life/en/faq/slajder/pryamougolnaya-zagotovka/',
    'section_icon' => '',
    'dop' => '',
    'hasImage' => '1',
    'summary' => '',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'Прямоугольная заготовка',
    'keywords' => 'Прямоугольная заготовка',
    'description' => 'Прямоугольная заготовка',
    'templateName' => '',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '1',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 11:48:07',
    'modifiedBy' => '9',
    'modifiedOn' => '2021-06-02 11:49:03',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '0',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
      0 => '988',
      1 => '991',
    ),
    'childLevels' => 0,
    'level' => 3,
    'path' => 'http://secondworld.life/en/faq/slajder/pryamougolnaya-zagotovka',
    'dir' => 'faq/slajder/pryamougolnaya-zagotovka',
  ),
  989 => 
  array (
    'sectionId' => '989',
    'parentId' => '0',
    'name' => 'About us',
    'alias' => '#about',
    'fileName' => 'about-us',
    'type' => 'tree',
    'type_content' => 'products',
    'url' => 'http://secondworld.life/en/about-us/',
    'section_icon' => '',
    'dop' => 'SECONDWORLD',
    'hasImage' => '1',
    'summary' => '<p>Second<span class="text-primary">world</span></p>',
    'content' => '',
    'content_two' => '',
    'status' => 'visible',
    'meta_title' => 'About us',
    'keywords' => 'About us',
    'description' => 'About us',
    'templateName' => 'section-contacts.tpl',
    'subTemplateName' => '',
    'artTemplateName' => '',
    'isCached' => '0',
    'cacheTime' => '1',
    'cachePeriod' => '86400',
    'commentsEnabled' => '0',
    'subIsCached' => '0',
    'subCacheTime' => '1',
    'subCachePeriod' => '86400',
    'subCommentsEnabled' => '0',
    'artIsCached' => '0',
    'artCacheTime' => '1',
    'artCachePeriod' => '86400',
    'sortOrder' => '11',
    'addedBy' => '9',
    'addedOn' => '2021-06-02 10:05:42',
    'modifiedBy' => '1',
    'modifiedOn' => '2022-08-16 07:21:10',
    'toSlider' => '0',
    'toMain' => '0',
    'top_menu' => '1',
    'footer_menu' => '0',
    'top_submenu' => '0',
    'photo_gallery' => '1',
    'footerMenu' => '0',
    'menus' => '',
    'isFeatured' => '0',
    'block' => '',
    'parents' => 
    array (
    ),
    'childLevels' => 0,
    'level' => 1,
    'path' => 'http://secondworld.life/en/about-us',
    'dir' => 'about-us',
  ),
);
$smarty->assignByRef('SECTIONS', $SECTIONS);
?>